// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";


console.log("DEBUG: DATABASE_URL length:", process.env["DATABASE_URL"]?.length);
console.log("DEBUG: DATABASE_URL value (first 10 chars):", process.env["DATABASE_URL"]?.substring(0, 10));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
